services:
    pim_catalog.association.class_resolver:
        class: 'Pim\Component\Catalog\Association\AssociationClassResolver'
        arguments:
            -
                Pim\Component\Catalog\Model\ProductInterface: Pim\Component\Catalog\Model\ProductAssociation
                Pim\Component\Catalog\Model\ProductModelInterface: Pim\Component\Catalog\Model\ProductModelAssociation

    pim_catalog.association.missing_association_adder:
        class: 'Pim\Component\Catalog\Association\MissingAssociationAdder'
        arguments:
            - '@pim_catalog.repository.association_type'
            - '@pim_catalog.association.class_resolver'
